// mockTickets.tsx

export interface Ticket {
  id: string;
  title: string;
  creator: string;
  assignee: string;
  status: "open" | "in-progress" | "closed" | "resolved";
  priority: "low" | "medium" | "high" | "critical";
  userGroup: string;
  project: string;
  description: string;
  createdAt: string;
  updatedAt: string;
}

const mockTickets: Ticket[] = [
  {
    id: "1",
    title: "Fix login bug",
    creator: "john.doe@example.com",
    assignee: "jane.smith@example.com",
    status: "open",
    priority: "high",
    userGroup: "Development",
    project: "Website Redesign",
    description: "Users are unable to log in with their credentials.",
    createdAt: new Date("2023-09-01T10:00:00Z").toISOString(),
    updatedAt: new Date("2023-09-02T12:00:00Z").toISOString(),
  },
  {
    id: "2",
    title: "Update user profile page",
    creator: "jane.smith@example.com",
    assignee: "john.doe@example.com",
    status: "in-progress",
    priority: "medium",
    userGroup: "Design",
    project: "User Experience",
    description: "Redesign the user profile page to improve UX.",
    createdAt: new Date("2023-09-03T09:30:00Z").toISOString(),
    updatedAt: new Date("2023-09-04T11:45:00Z").toISOString(),
  },
  {
    id: "3",
    title: "Server maintenance",
    creator: "john.doe@example.com",
    assignee: "jane.smith@example.com",
    status: "closed",
    priority: "low",
    userGroup: "Support",
    project: "Website Redesign",
    description: "Scheduled server maintenance on the weekend.",
    createdAt: new Date("2023-09-05T08:15:00Z").toISOString(),
    updatedAt: new Date("2023-09-06T10:30:00Z").toISOString(),
  },
  {
    id: "4",
    title: "Add new feature to dashboard",
    creator: "jane.smith@example.com",
    assignee: "john.doe@example.com",
    status: "resolved",
    priority: "critical",
    userGroup: "Development",
    project: "Website Redesign",
    description: "Implement the new analytics feature on the dashboard.",
    createdAt: new Date("2023-09-07T07:00:00Z").toISOString(),
    updatedAt: new Date("2023-09-08T09:00:00Z").toISOString(),
  },
  {
    id: "5",
    title: "Email notifications not working",
    creator: "john.doe@example.com",
    assignee: "jane.smith@example.com",
    status: "open",
    priority: "high",
    userGroup: "Support",
    project: "Website Redesign",
    description: "Users are not receiving email notifications.",
    createdAt: new Date("2023-09-09T06:45:00Z").toISOString(),
    updatedAt: new Date("2023-09-10T08:30:00Z").toISOString(),
  },
  {
    id: "6",
    title: "Optimize database queries",
    creator: "jane.smith@example.com",
    assignee: "john.doe@example.com",
    status: "in-progress",
    priority: "medium",
    userGroup: "Development",
    project: "Backup",
    description: "Optimize slow database queries for better performance.",
    createdAt: new Date("2023-09-11T05:30:00Z").toISOString(),
    updatedAt: new Date("2023-09-12T07:15:00Z").toISOString(),
  },
  {
    id: "7",
    title: "Design new landing page",
    creator: "john.doe@example.com",
    assignee: "jane.smith@example.com",
    status: "closed",
    priority: "low",
    userGroup: "Design",
    project: "User Experience",
    description: "Create a new design for the landing page.",
    createdAt: new Date("2023-09-13T04:20:00Z").toISOString(),
    updatedAt: new Date("2023-09-14T06:10:00Z").toISOString(),
  },
  {
    id: "8",
    title: "Fix mobile responsiveness",
    creator: "jane.smith@example.com",
    assignee: "john.doe@example.com",
    status: "resolved",
    priority: "high",
    userGroup: "Development",
    project: "Website Redesign",
    description: "Ensure the site is fully responsive on mobile devices.",
    createdAt: new Date("2023-09-15T03:10:00Z").toISOString(),
    updatedAt: new Date("2023-09-16T05:00:00Z").toISOString(),
  },
  {
    id: "9",
    title: "Update API documentation",
    creator: "john.doe@example.com",
    assignee: "jane.smith@example.com",
    status: "open",
    priority: "medium",
    userGroup: "Development",
    project: "User Experience",
    description: "Update the API documentation with the latest changes.",
    createdAt: new Date("2023-09-17T02:00:00Z").toISOString(),
    updatedAt: new Date("2023-09-18T03:50:00Z").toISOString(),
  },
  {
    id: "10",
    title: "Implement user feedback",
    creator: "jane.smith@example.com",
    assignee: "john.doe@example.com",
    status: "in-progress",
    priority: "critical",
    userGroup: "Development",
    project: "User Experience",
    description: "Incorporate user feedback into the next release.",
    createdAt: new Date("2023-09-19T01:00:00Z").toISOString(),
    updatedAt: new Date("2023-09-20T02:40:00Z").toISOString(),
  },
  {
    id: "11",
    title: "Security audit",
    creator: "john.doe@example.com",
    assignee: "jane.smith@example.com",
    status: "closed",
    priority: "high",
    userGroup: "Development",
    project: "Website Redesign",
    description: "Conduct a security audit of the application.",
    createdAt: new Date("2023-09-21T00:00:00Z").toISOString(),
    updatedAt: new Date("2023-09-22T01:30:00Z").toISOString(),
  },
  {
    id: "12",
    title: "Fix CSS issues",
    creator: "jane.smith@example.com",
    assignee: "john.doe@example.com",
    status: "resolved",
    priority: "low",
    userGroup: "Design",
    project: "Website Redesign",
    description: "Resolve various CSS issues across the site.",
    createdAt: new Date("2023-09-23T23:00:00Z").toISOString(),
    updatedAt: new Date("2023-09-24T00:20:00Z").toISOString(),
  },
  {
    id: "13",
    title: "Add unit tests",
    creator: "john.doe@example.com",
    assignee: "jane.smith@example.com",
    status: "open",
    priority: "medium",
    userGroup: "Testing",
    project: "Backup",
    description: "Add unit tests for the new features.",
    createdAt: new Date("2023-09-25T22:00:00Z").toISOString(),
    updatedAt: new Date("2023-09-26T23:10:00Z").toISOString(),
  },
  {
    id: "14",
    title: "Improve accessibility",
    creator: "jane.smith@example.com",
    assignee: "john.doe@example.com",
    status: "in-progress",
    priority: "high",
    userGroup: "Development",
    project: "Website Redesign",
    description: "Enhance the accessibility of the website.",
    createdAt: new Date("2023-09-27T21:00:00Z").toISOString(),
    updatedAt: new Date("2023-09-28T22:05:00Z").toISOString(),
  },
  {
    id: "15",
    title: "Database backup",
    creator: "john.doe@example.com",
    assignee: "jane.smith@example.com",
    status: "closed",
    priority: "critical",
    userGroup: "Support",
    project: "Backup",
    description: "Perform a full backup of the database.",
    createdAt: new Date("2023-09-29T20:00:00Z").toISOString(),
    updatedAt: new Date("2023-09-30T21:55:00Z").toISOString(),
  },
];

export default mockTickets;